sudo: required
services:
  - docker

before_install:
  - docker build -t neha/docker_react -f Dockerfile.dev .

script:
  - docker run  -e CI=true neha/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-954516000444"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: 
    secure : "$AWS_SECRET_KEY"